export const movies = [
  {
    id: 2,
    posterURL: require("./img/0.jpg"),
    genres: "Comedy",
    rating: 7,
    title: "Dumb and Dumber",
    trailer: 'https://www.youtube.com/watch?v=dmNddThxi4c',
    description: "Dumb and Dumber is a 1994 American buddy comedy film directed by Peter Farrelly, who cowrote the screenplay with Bobby Farrelly and Bennett Yellin. It is the first installment in the Dumb and Dumber franchise. Starring Jim Carrey and Jeff Daniels, it tells the story of Lloyd Christmas (Carrey) and Harry Dunne (Daniels), two dumb but well-meaning friends from Providence, Rhode Island, who set out on a cross-country trip to Aspen, Colorado, to return a briefcase full of money to its owner, thinking it was abandoned as a mistake though it was actually left as a ransom. Lauren Holly, Karen Duffy, Mike Starr, Charles Rocket, and Teri Garr play supporting roles.",
  },
  {
    id: 3,
    posterURL: require("./img/1.jpg"),
    genres: "Action",
    rating: 9.5,
    title: "The Night Agent",
    trailer: 'https://www.youtube.com/watch?v=YDbnY9Obsfs',
    description: "The Night Agent is an American action thriller television series created by Shawn Ryan based on the novel of the same name by Matthew Quirk. Starring Gabriel Basso in the title role, it premiered on Netflix on March 23, 2023. The series emerged as the third-most-viewed debuting series on Netflix in its first four days, and within a week it was renewed for a second season. Within three weeks, it became the streamer's ninth-most-viewed series.",
  },
  {
    id: 1,
    posterURL: require("./img/2.jpg"),
    genres: "Romantic",
    rating: 6,
    title: "Cyrano (2022)",
    trailer: 'https://www.youtube.com/watch?v=5e8apSFDXsQ',
    description: "Cyrano is a 2021 musical romantic drama film directed by Joe Wright and with a screenplay by Erica Schmidt, based on Schmidt's 2018 stage musical of the same name, itself based on the 1897 Edmond Rostand play Cyrano de Bergerac. The film stars Peter Dinklage, Haley Bennett, Kelvin Harrison Jr., and Ben Mendelsohn.",
  },
  {
    id: 4,
    posterURL: require("./img/3.jpg"),
    genres: "Adventure",
    rating: 6,
    title: "The Little Mermaid",
    trailer: 'https://www.youtube.com/watch?v=kpGo2_d3oYE',
    description: '"The Little Mermaid" (Danish: Den lille havfrue) is a literary fairy tale written by the Danish author Hans Christian Andersen, first published in 1837 as part of a collection of fairy tales for children. The story follows the journey of a young mermaid who is willing to give up her life in the sea as a mermaid to gain a human soul.',
  },
  {
    id: 5,
    posterURL: require("./img/4.jpg"),
    genres: "Comedy",
    rating: 3.5,
    title: "Groundhog Day (1993)",
    trailer: 'https://www.youtube.com/watch?v=GncQtURdcE4',
    description: "Groundhog Day is a 1993 American fantasy comedy film directed by Harold Ramis from a screenplay by him and Danny Rubin. Starring Bill Murray, Andie MacDowell, and Chris Elliott, it tells the story of Phil Connors (Murray), a cynical television weatherman covering the annual Groundhog Day event in Punxsutawney, Pennsylvania, who becomes trapped in a time loop, forcing him to relive February 2 repeatedly. The film also features Stephen Tobolowsky, Brian Doyle-Murray, Marita Geraghty, Angela Paton, Rick Ducommun, Rick Overton, and Robin Duke.",
  },
  {
    id: 8,
    posterURL: require("./img/5.jpg"),
    genres: "Adventure",
    rating: 10,
    title: "Avatar",
    trailer: 'https://www.youtube.com/watch?v=sMyALuL6Qy0',
    description: "Avatar (marketed as James Cameron's Avatar) is a 2009 epic science fiction film directed, written, co-produced, and co-edited by James Cameron and starring Sam Worthington, Zoe Saldana, Stephen Lang, Michelle Rodriguez, and Sigourney Weaver. It is the first installment in the Avatar film series. It is set in the mid-22nd century, when humans are colonizing Pandora, a lush habitable moon of a gas giant in the Alpha Centauri star system, in order to mine the valuable mineral unobtanium.[a] The expansion of the mining colony threatens the continued existence of a local tribe of Na'vi, a humanoid species indigenous to Pandora. The title of the film refers to a genetically engineered Na'vi body operated from the brain of a remotely located human that is used to interact with the natives of Pandora",
  },
  {
    id: 6,
    posterURL: require("./img/6.jpg"),
    genres: "Romantic",
    rating: 2,
    title: "Decision to Leave",
    trailer: 'https://www.youtube.com/watch?v=d9BR3Z_-Hh8',
    description: "In April 2022, the film was selected to compete for the Palme d'Or at the 2022 Cannes Film Festival, where Park Chan-wook won Best Director. Decision to Leave was released theatrically on 29 June 2022 in South Korea. The film received critical acclaim and was nominated for numerous awards, including Best Film Not in the English Language and Best Direction at the 76th British Academy Film Awards. It was selected as the South Korean entry for the Best International Feature Film at the 95th Academy Awards, making the December shortlist. It was also named one of the top 5 international films of 2022 by the National Board of Review",
  },
  {
    id: 7,
    posterURL: require("./img/7.jpg"),
    genres: "Action",
    rating: 5,
    title: "The Mandalorian",
    trailer: 'https://www.youtube.com/watch?v=aOC8E8z_ifw',
    description: "The Mandalorian is an American space Western television series created by Jon Favreau for the streaming service Disney+. It is the first live-action series in the Star Wars franchise, beginning five years after the events of Return of the Jedi (1983), and stars Pedro Pascal as the title character, a lone bounty hunter who goes on the run to protect the Force-sensitive child Grogu. Starting in the third season, Katee Sackhoff also stars as Mandalorian Bo-Katan Kryze, following her appearance in the second season.",
  },
];
